### ISSUE TITLE
Context menu to add resources to module

### ISSUE THREAD

**Issue by bjornbak** [mediaworx/opencms-intellijplugin#3] opened 2015-10-01 08:58 UTC
When I create a new file below the src/main/vfs and do a sync of the module the plugin PUSH'es the files into opencms and pull a new ocmsfile.xml into src/main/manifest. Perfect!

But if I add a directory it is not pushed into opencms.

To add a directory I have to go into the workplace and add the directory then I can sync the directory into src/main/vfs and the corresponding ocmsfolder.xml into src/main/manifest.

I would be great if was handled automatically like files or via a context menu.

Even more if I add a directory outside the directories mentioned as resources in manifest.xml I have to either manually change manifest_stub.xml or in the opencms workplace edit the Module Resources. It would be great to have a context menu for folders under /src/main/vfs but not in the resource section of manifest_stub.xml where I can those to add it to manifest_stub.xml.

**Comment by kaiwidmann** [comment] 2015-10-01 09:54
Hi Bjorn, 

sorry, I can't reproduce this behaviour. If I create a folder/directory somewhere within a resource path, it get's pushed all right and the ocmsfolder.xml file is pulled. Please can you describe with a little more detail what you are doing. Do you create the folder in IntelliJ or in the File System? If it's the latter, IntelliJ might just not know about the new directory when you're syncing/pushing (IntelliJ has a virtual file system of its own that's not always in sync with the real file system). If so then hitting the IntelliJ sync button (two blue circled arrows beside the save button) before doing the OpenCms push might help.

Concerning your wish to add resources to the module via a context menu, I think that's a good idea and I'll put that on the feature wish list, but I don't know when it will be done or if at all.

Cheers

Kai

**Comment by bjornbak** [comment] 2015-10-01 12:50
I can't reproduce it either now. I don't know what I have done wrong might be an file system copy as you suggest or maybe the folder was outside the resource paths.

I have changed the subject line to a match the feature request of adding new resource folders.

**Comment by kaiwidmann** [comment] 2016-06-24 15:15
I'm closing this, since new resources (and also new folders) are added to OpenCms "on the fly" during sync and the meta data is also pulled automatically.

**Closed as completed by kaiwidmann** 2016-06-24 15:15 UTC
Labels: feature request
